package io.ashton.async.client.widgets;

import com.google.gwt.user.client.ui.Composite;
import com.google.gwt.user.client.ui.InlineLabel;

public class MySPTestWidget extends Composite {


  public MySPTestWidget(){
    String text = "APSP!" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
        "APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!APSP!AAPSP!APSP!APSP!APSP!A" +
    		"PSP!PSP!";
    InlineLabel l = new InlineLabel(text);
    initWidget(l);
  }
}
